// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sample_sparsity
arma::umat sample_sparsity(arma::mat y, arma::mat factors, arma::vec tau, arma::vec theta, arma::umat delta, arma::uvec pivots, arma::vec alpha, arma::vec beta, arma::vec inner_prod_y);
RcppExport SEXP _BayesSFA_sample_sparsity(SEXP ySEXP, SEXP factorsSEXP, SEXP tauSEXP, SEXP thetaSEXP, SEXP deltaSEXP, SEXP pivotsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP inner_prod_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type factors(factorsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type pivots(pivotsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type inner_prod_y(inner_prod_ySEXP);
    rcpp_result_gen = Rcpp::wrap(sample_sparsity(y, factors, tau, theta, delta, pivots, alpha, beta, inner_prod_y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesSFA_sample_sparsity", (DL_FUNC) &_BayesSFA_sample_sparsity, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesSFA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
