# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_log_likelihood_ratio <- function(delta, l_new, j, factors, y, inner_prod_y, alpha, beta, theta) {
    .Call(`_BayesSFA_compute_log_likelihood_ratio`, delta, l_new, j, factors, y, inner_prod_y, alpha, beta, theta)
}

sample_loadings_variances <- function(y, factors, delta, theta, alpha, beta, inner_prod_y) {
    .Call(`_BayesSFA_sample_loadings_variances`, y, factors, delta, theta, alpha, beta, inner_prod_y)
}

sample_sparsity <- function(y, factors, tau, theta, delta, pivots, alpha, beta, inner_prod_y) {
    .Call(`_BayesSFA_sample_sparsity`, y, factors, tau, theta, delta, pivots, alpha, beta, inner_prod_y)
}

