# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_sparsity <- function(y, factors, tau, theta, delta, pivots, alpha, beta, inner_prod_y) {
    .Call(`_BayesSFA_sample_sparsity`, y, factors, tau, theta, delta, pivots, alpha, beta, inner_prod_y)
}

